// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpRHvjW8P4dhdvgl_Kmz3T3KoHTG77Hs',
    appId: '1:878966573436:web:4bfc4716bcb59bbb20bcf9',
    messagingSenderId: '878966573436',
    projectId: 'pata-aa318',
    authDomain: 'pata-aa318.firebaseapp.com',
    storageBucket: 'pata-aa318.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHCRXOAqMpVVDGQ19IrCT-z54watsyUjY',
    appId: '1:878966573436:android:be862e41a719464020bcf9',
    messagingSenderId: '878966573436',
    projectId: 'pata-aa318',
    storageBucket: 'pata-aa318.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbY4lI4XzCr77NOHGNxy5Q6ZN-4uttm8',
    appId: '1:878966573436:ios:13731c225915ce2120bcf9',
    messagingSenderId: '878966573436',
    projectId: 'pata-aa318',
    storageBucket: 'pata-aa318.firebasestorage.app',
    iosBundleId: 'com.example.projetoPata',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkbY4lI4XzCr77NOHGNxy5Q6ZN-4uttm8',
    appId: '1:878966573436:ios:13731c225915ce2120bcf9',
    messagingSenderId: '878966573436',
    projectId: 'pata-aa318',
    storageBucket: 'pata-aa318.firebasestorage.app',
    iosBundleId: 'com.example.projetoPata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpRHvjW8P4dhdvgl_Kmz3T3KoHTG77Hs',
    appId: '1:878966573436:web:b30dbe3c1db2d55720bcf9',
    messagingSenderId: '878966573436',
    projectId: 'pata-aa318',
    authDomain: 'pata-aa318.firebaseapp.com',
    storageBucket: 'pata-aa318.firebasestorage.app',
  );
}
